server.port=7070
app.url=http://localhost:7070
amazon.aws.accesskey=dummy
amazon.aws.secretkey=dummy
amazon.dynamodb.region=eu-central-1
amazon.dynamodb.local.port=8000
amazon.dynamodb.sqlite.lib.path=${user.home}/.m2/repository/com/almworks/sqlite4java/libsqlite4java-linux-amd64/1.0.392
